import { Geist, Geist_Mono } from "next/font/google";
import { Outfit , Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import Subscribe from "@/Components/Subscribe/Subscribe";
import SmoothScroll from "@/Components/SmoothScroll";
import AnimateOnScroll from "@/Components/AnimateOnScroll";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight:["400"],
  subsets:["latin"],
  display:"swap"
}) ;

// const poppins = Poppins({
//   weight:["400"],
//   subsets:["latin"]
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} `}
      >
        <SmoothScroll>
          <AnimateOnScroll>
        <Header/>
        <main>
        {children}
        <Subscribe/>
        </main>   
        <Footer/>
        </AnimateOnScroll>
        </SmoothScroll>
      </body>
    </html>
  );
}
